# Site settings
title: Learnings
description: >
baseurl: "/learnings"
url: "localhost:4000"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title.html